version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: health-ai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=health-ai

  redis:
    image: redis:latest
    container_name: health-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
