"""Initial migration

Revision ID: 1e801fbc3d91
Revises: 
Create Date: 2024-11-25 22:15:49.404969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1e801fbc3d91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_prescriptions_id')

    op.drop_table('prescriptions')
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_index('ix_vital_signs_id')

    op.drop_table('vital_signs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_id')

    op.drop_table('appointments')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_id')

    op.drop_table('predictions')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_id')

    op.drop_table('patients')
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_history_id')

    op.drop_table('medical_history')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oxygen_saturation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('waist_circumference', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hemoglobin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_factors', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('blood_pressure_systolic',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('blood_pressure_diastolic',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('heart_rate',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('respiratory_rate',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('alcohol_consumption')
        batch_op.drop_column('smoking_status')
        batch_op.drop_column('physical_activity_level')
        batch_op.drop_column('allergies')
        batch_op.drop_column('chronic_conditions')
        batch_op.drop_column('medications')

    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.alter_column('cardiovascular_risk',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('diabetes_risk',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('respiratory_risk',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cancer_risk',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('risk_factors',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('recommendations',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('model_version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('mental_health_risk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mental_health_risk', sa.FLOAT(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('model_version',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('recommendations',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('risk_factors',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('cancer_risk',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('respiratory_risk',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('diabetes_risk',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cardiovascular_risk',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medications', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('chronic_conditions', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('physical_activity_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('smoking_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('alcohol_consumption', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('respiratory_rate',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('heart_rate',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('blood_pressure_diastolic',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('blood_pressure_systolic',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('risk_factors')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('hemoglobin')
        batch_op.drop_column('cholesterol_total')
        batch_op.drop_column('waist_circumference')
        batch_op.drop_column('oxygen_saturation')

    op.create_table('medical_history',
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=100), nullable=False),
    sa.Column('diagnosis_date', sa.DATE(), nullable=True),
    sa.Column('treatment', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('documents', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.create_index('ix_medical_history_id', ['id'], unique=False)

    op.create_table('patients',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=5), nullable=True),
    sa.Column('allergies', sqlite.JSON(), nullable=True),
    sa.Column('emergency_contact', sqlite.JSON(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('insurance_info', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_id', ['id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('symptoms', sqlite.JSON(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('oxygen_level', sa.FLOAT(), nullable=True),
    sa.Column('additional_notes', sa.VARCHAR(), nullable=True),
    sa.Column('prediction', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('recommendations', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_predictions_id', ['id'], unique=False)

    op.create_table('appointments',
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('virtual', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_id', ['id'], unique=False)

    op.create_table('vital_signs',
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('heart_rate', sa.INTEGER(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.INTEGER(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.INTEGER(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('respiratory_rate', sa.INTEGER(), nullable=True),
    sa.Column('oxygen_saturation', sa.INTEGER(), nullable=True),
    sa.Column('blood_glucose', sa.FLOAT(), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.create_index('ix_vital_signs_id', ['id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=50), nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('refills_remaining', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('ix_prescriptions_id', ['id'], unique=False)

    # ### end Alembic commands ###
